### ISSUE TITLE
upgrade to support dbt-core v1.6.0

### ISSUE THREAD

**Issue by dataders** [dbeatty10/dbt-mysql#155]
## Background 

Minor version `v1.6` is targeted for final release on July 27, 2023. As a maintainer of a dbt adapter, we strongly encourage you to release a corresponding minor version increment to ensure users of your adapter can make use of this new minor version.

## How to upgrade

https://github.com/dbt-labs/dbt-core/discussions/7213 is an open discussion with more detailed information. If you have questions, please put them there!

The above linked guide has more information, but below is a high-level checklist of work that would enable a successful 1.6.0 release of your adapter:

```[tasklist]
### Tasks
- [ ] SUPPORT: materialized views
- [ ] SUPPORT: new `clone` command
- [ ] BEHIND THE SCENES: Drop support for Python 3.7 (if you haven't already)
- [ ] BEHIND THE SCENES: new arg for `adapter.execute()`
- [ ] BEHIND THE SCENES: ensure support for revamped `dbt debug``
- [ ] BEHIND THE SCENES: Add support for new/modified relevant tests
```

## the next minor release: `1.7.0`

FYI, `dbt-core==1.7.0` is expected to be released on October 12, 2023 in time for [Coalesce](https://coalesce.getdbt.com/), the annual analytics engineering conference!

**Comment by im-AMS** [comment]
@dbeatty is there a chance that we can see a new release supporting py3.10 or py3.11?
its been a while since there was an update, like what @ian-lewis-d said, its getting very inconvenient.

**Comment by azngeek** [comment]
Can we have an update on this one? What can we do to make this happen?

**Comment by outinim** [comment]
Yeah +1 here, what can we do to update dbt-core for MySQL @dbeatty10 @dbeatty, I'm sure a lot of people are using MySQL and it's frustrating to not have `dbt-core >= 1.5` to for exemple ro run it with airflow2 or other tools. I'm open to help for the upgrade (just need a little of help to start :) )

**Comment by mwallace582** [comment]
This issue has been partially addressed in an alpha version of dbt-mysql (v1.6.0a1).

While this release of the adapter is compatible with dbt-core 1.6 and supports basic functionality, we have not yet fully addressed the checklist items for full 1.6 support.
